"""add current_offset to update_log

Revision ID: 0ae62c98798d
Revises: f6e6364de14e
Create Date: 2026-09-20 16:20:18.403055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae62c98798d'
down_revision: Union[str, Sequence[str], None] = 'f6e6364de14e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('update_log', sa.Column('current_offset', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('update_log', 'current_offset')
    # ### end Alembic commands ###
