"""wishlist changes

Revision ID: 13d24a21dec0
Revises: 96292766a2f0
Create Date: 2026-06-10 22:06:56.163852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d24a21dec0'
down_revision: Union[str, Sequence[str], None] = '96292766a2f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist', 'date')
    # ### end Alembic commands ###
