"""add update_log table

Revision ID: 1f334da1b7fa
Revises: a9ae2ecdb8bd
Create Date: 2026-09-18 20:46:02.445087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f334da1b7fa'
down_revision: Union[str, Sequence[str], None] = 'a9ae2ecdb8bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=False),
    sa.Column('games_updated', sa.Integer(), nullable=True),
    sa.Column('games_added', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('items_item_id_key'), 'items', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('items_item_id_key'), 'items', ['item_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('update_log')
    # ### end Alembic commands ###
