"""cover art

Revision ID: 21ed0badb9a4
Revises: 94fa24f409d0
Create Date: 2026-07-10 10:49:11.684102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ed0badb9a4'
down_revision: Union[str, Sequence[str], None] = '94fa24f409d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('art_url', sa.String(), nullable=True))
    op.add_column('items', sa.Column('collection', sa.Text(), nullable=True))
    op.add_column('items', sa.Column('collection_name', sa.Text(), nullable=True))
    op.drop_column('items', 'art')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('art', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('items', 'collection_name')
    op.drop_column('items', 'collection')
    op.drop_column('items', 'art_url')
    # ### end Alembic commands ###
