"""Add new collumn (small cover and big cover)

Revision ID: 282089f4364d
Revises: d38be4b0f093
Create Date: 2026-07-11 18:03:17.986829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282089f4364d'
down_revision: Union[str, Sequence[str], None] = 'd38be4b0f093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('small_cover', sa.String(), nullable=True))
    op.add_column('items', sa.Column('big_cover', sa.String(), nullable=True))
    op.drop_column('items', 'collection_name')
    op.drop_column('items', 'collection')
    op.drop_column('items', 'cover')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('cover', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('collection', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('collection_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('items', 'big_cover')
    op.drop_column('items', 'small_cover')
    # ### end Alembic commands ###
