"""longer reviews available

Revision ID: 4344dde8e19f
Revises: 8b22d39e8794
Create Date: 2026-08-01 18:00:08.683879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4344dde8e19f'
down_revision: Union[str, Sequence[str], None] = '8b22d39e8794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection', 'notes',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=750),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection', 'notes',
               existing_type=sa.String(length=750),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    # ### end Alembic commands ###
