"""added platform_id to wishlistList

Revision ID: 6a86bfbed862
Revises: db744f9a6617
Create Date: 2026-07-27 21:49:29.007501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a86bfbed862'
down_revision: Union[str, Sequence[str], None] = 'db744f9a6617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('platform_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'wishlist', 'platform_id', ['platform_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlist', type_='foreignkey')
    op.drop_column('wishlist', 'platform_id')
    # ### end Alembic commands ###
