"""add user_rating to collection

Revision ID: 701160b00b60
Revises: c6e713ae9f0c
Create Date: 2026-06-09 07:20:38.161915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701160b00b60'
down_revision: Union[str, Sequence[str], None] = 'c6e713ae9f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('user_rating', sa.Float(), nullable=True))
    op.add_column('collection', sa.Column('played', sa.Boolean(), nullable=True))
    op.alter_column('collection', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('collection_item_id_fkey'), 'collection', type_='foreignkey')
    op.drop_column('collection', 'price_paid')
    op.drop_column('collection', 'condition')
    op.drop_column('collection', 'user_media')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('user_media', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('collection', sa.Column('condition', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('collection', sa.Column('price_paid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('collection_item_id_fkey'), 'collection', 'items', ['item_id'], ['item_id'])
    op.alter_column('collection', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('collection', 'played')
    op.drop_column('collection', 'user_rating')
    # ### end Alembic commands ###
