"""modified items

Revision ID: 7743b07fdbc1
Revises: 512ad6c14f6c
Create Date: 2026-05-29 10:55:42.766102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7743b07fdbc1'
down_revision: Union[str, Sequence[str], None] = '512ad6c14f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('cover', sa.String(), nullable=True))
    op.add_column('items', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('items', 'platform',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('items', 'categories',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('items', 'genre',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('items', 'media')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('media', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('items', 'genre',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('items', 'categories',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('items', 'platform',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('items', 'description')
    op.drop_column('items', 'cover')
    # ### end Alembic commands ###
