"""make platform_id and platform in collection list

Revision ID: 8b22d39e8794
Revises: a3162e3640ee
Create Date: 2026-07-28 21:56:46.405912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b22d39e8794'
down_revision: Union[str, Sequence[str], None] = 'a3162e3640ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('platform', sa.String(), nullable=True))
    op.add_column('collection', sa.Column('platform_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'collection', 'platform_id', ['platform_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.drop_column('collection', 'platform_id')
    op.drop_column('collection', 'platform')
    # ### end Alembic commands ###
