"""wishlist changes

Revision ID: 96292766a2f0
Revises: fe4925e18fcd
Create Date: 2026-06-10 21:50:16.629184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96292766a2f0'
down_revision: Union[str, Sequence[str], None] = 'fe4925e18fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('platform', sa.String(), nullable=True))
    op.drop_column('wishlist', 'price_usd')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('price_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('wishlist', 'platform')
    # ### end Alembic commands ###
