"""rating fields and igdb id 

Revision ID: 99d9ea95044d
Revises: d14dfa16f827
Create Date: 2026-08-02 23:09:36.175131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d9ea95044d'
down_revision: Union[str, Sequence[str], None] = 'd14dfa16f827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('age_rating', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('age_category', sa.Integer(), nullable=True))
    op.alter_column('items', 'rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_column('items', 'rating_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('rating_category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('items', 'rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('items', 'age_category')
    op.drop_column('items', 'age_rating')
    # ### end Alembic commands ###
