"""make platform_id nullable in wishlist

Revision ID: a3162e3640ee
Revises: 57d490f3f261
Create Date: 2026-07-28 19:51:33.424559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3162e3640ee'
down_revision: Union[str, Sequence[str], None] = '57d490f3f261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wishlist', 'platform_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wishlist', 'platform_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
