"""add password attempts traking to users

Revision ID: a45b9467f2d5
Revises: f2acb62292f1
Create Date: 2026-05-28 09:58:43.563028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45b9467f2d5'
down_revision: Union[str, Sequence[str], None] = 'f2acb62292f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_attempt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_attempt')
    op.drop_column('users', 'password_attempts')
    # ### end Alembic commands ###
