"""dealing with unique name constraint(removed)

Revision ID: be2c6849ce33
Revises: cb5258bc4c48
Create Date: 2026-08-03 20:56:41.121859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be2c6849ce33'
down_revision: Union[str, Sequence[str], None] = 'cb5258bc4c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('items_item_name_key'), 'items', type_='unique')
    op.create_unique_constraint(None, 'items', ['igdb_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='unique')
    op.create_unique_constraint(op.f('items_item_name_key'), 'items', ['item_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
