"""deleting age col

Revision ID: c901c2936999
Revises: be2c6849ce33
Create Date: 2026-08-04 22:23:02.988906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c901c2936999'
down_revision: Union[str, Sequence[str], None] = 'be2c6849ce33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'age_rating')
    op.drop_column('items', 'age_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('age_category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('age_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
