"""rating fields and igdb id 

Revision ID: d14dfa16f827
Revises: 4344dde8e19f
Create Date: 2026-08-02 22:48:21.231899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14dfa16f827'
down_revision: Union[str, Sequence[str], None] = '4344dde8e19f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('igdb_id', sa.Integer(), nullable=False))
    op.add_column('items', sa.Column('rating_category', sa.Integer(), nullable=True))
    op.alter_column('items', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'rating',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('items', 'rating_category')
    op.drop_column('items', 'igdb_id')
    # ### end Alembic commands ###
