"""excluding collection stuff

Revision ID: d38be4b0f093
Revises: 21ed0badb9a4
Create Date: 2026-07-10 21:10:07.073309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd38be4b0f093'
down_revision: Union[str, Sequence[str], None] = '21ed0badb9a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('art', sa.String(), nullable=True))
    op.drop_column('items', 'art_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('art_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('items', 'art')
    # ### end Alembic commands ###
