"""items platform and items genre

Revision ID: db744f9a6617
Revises: 1109d104e848
Create Date: 2026-07-14 21:39:15.925372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db744f9a6617'
down_revision: Union[str, Sequence[str], None] = '1109d104e848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre_id.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platform_id.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'genre_id', ['id'])
    op.create_unique_constraint(None, 'platform_id', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'platform_id', type_='unique')
    op.drop_constraint(None, 'genre_id', type_='unique')
    op.drop_table('platform_games')
    op.drop_table('genre_games')
    # ### end Alembic commands ###
