"""cover art

Revision ID: f12ec61607ad
Revises: 13d24a21dec0
Create Date: 2026-07-10 10:43:29.754156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f12ec61607ad'
down_revision: Union[str, Sequence[str], None] = '13d24a21dec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('art', sa.String(), nullable=True))
    op.drop_column('items', 'categories')
    op.drop_column('items', 'region')
    op.drop_column('items', 'variant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('variant', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('region', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('categories', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('items', 'art')
    # ### end Alembic commands ###
